restylers:
  - isort:
      enabled: false
  - reorder-python-imports:
      enabled: false
  - isort:
      enabled: false
  - prettier-markdown:
      arguments: ["--prose-wrap", "never"]
  - "*"
  - black
